# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 094dc6f8ea39c4ec512ef0213255975ecbcf36ccd4ada7a270b9fd6a0b12b99a46ff97afbc6a5949f86ba6e31e89ed56ae49f036a08e3f27d75a6be2d1594ee9

test:
  secret_key_base: e1fbe9055c3c94063fe02b19c7a37131e6de940c98a39b040522dac7f0eee355165497be83e98c00a2b8f9c10b5e3b0c886054fab73b8fe7cffd742bed217287

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
